---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metademo-controller
  namespace: controllers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metademo-controller
  template:
    metadata:
      labels:
        app: metademo-controller
    spec:
      containers:
      - name: controller
        image: metadem:0.0.21

---

apiVersion: v1
kind: Service
metadata:
  name: metademo-controller
  namespace: controllers
spec:
  selector:
    app: metademo-controller
  ports:
  - port: 8080
